### ISSUE TITLE
Damage

### ISSUE THREAD

**Issue by Nivekruitert** [FiveM-Scripts/CorruptSnail-Gamemode#11]
All my players got a one hit kill from the zombie peds. Is there a way to make a line in the config to edit their melee damage?

**Comment by Switty6** [comment]
Yes. Edit in cl_zombies line 34

**Comment by Nivekruitert** [comment]
Thnx!

**Comment by Kev-Lar666** [comment]
im a dumbass, would it just be the 9999 value lowered? Tried it but was still getting 1shot with
SetAiMeleeWeaponDamageModifier(0.0)

**Comment by Switty6** [comment]
Try 1 not 0.
