### ISSUE TITLE
Script for zombies 

### ISSUE THREAD

**Issue by Caydos** [FiveM-Scripts/CorruptSnail-Gamemode#13]
Hi guys can somebody tell me how to disable zombies spawning around and in safe zones ? and also how to add different skins for zombies .

**Comment by ghermans** [comment]
You can change the skin for the zombies in your config file.
https://github.com/FiveM-Scripts/CorruptSnail-Gamemode/blob/rewrite/config.lua#L72

**Comment by Caydos** [comment]
yes but i want to make different skins i don't want to see only one type of zombies

**Comment by ghermans** [comment]
Unfortunately, this option is not available, nor are there any plans to add it.

**Comment by Caydos** [comment]
Ok and you don't answer me about disable their spawn in safe zones so have you something to help me pls ?

**Comment by Caydos** [comment]
And i don't think that a lot of peoples say it to you but you did a good job for this script .
