### ISSUE TITLE
Zombies will not spawn if > 1 player together

### ISSUE THREAD

**Issue by Kevin0M16** [FiveM-Scripts/CorruptSnail-Gamemode#15]
When more than one person is near each other, say driving around, no zombies will spawn. When solo or away from other players it works fine. Any ideas?

Great job btw.

I'm using the lua version.

**Comment by ghermans** [comment]
Is onesync enabled on your server?

**Comment by Kevin0M16** [comment]
Yes. I have onesync_enabled true in config. 

I have read through the issues here and have seen this mentioned before but without explanation. Do I need it enabled or disabled?

Could you offer insight into what onesync does and how it affects this?

Thank you.

Kevin

**Comment by Kevin0M16** [comment]
I’m new to lua but it seems Line 5 in cl_player, playerId seems to be an undefined variable and fixed the issue by changing playerId to mPlayerId

`local mServerId = GetPlayerServerId(playerId)`

**Comment by ghermans** [comment]
@pongo1231 can you verify this?

**Comment by pongo1231** [comment]
That was indeed an issue that slipped through, should fix the mentioned issue now.
