### ISSUE TITLE
Guards spawn with every player.

### ISSUE THREAD

**Issue by Switty6** [FiveM-Scripts/CorruptSnail-Gamemode#7]
A guard spawns for every player. For example if a player is on the server, there will be one guard on every coords set. If 2 or more players are on the server there will be 2 or more guards on every coords.

**Comment by ghost** [comment]
@Sup66 Do zombies spawn on your test server even with other connected players?

**Comment by Switty6** [comment]
Yes they do.

**Comment by Vathalla** [comment]
Are you using the lua or the c# version?

**Comment by ghost** [comment]
> Yes they do.

Are you using the lua or the c# version?

**Comment by Switty6** [comment]
I’m using lua.

**Comment by ghermans** [comment]
@Sup66 is it possible that you are enabled onesync on your server?

**Comment by Switty6** [comment]
No. It wasn't enabled.

**Comment by ghermans** [comment]
This issue should be fixed now.
