### ISSUE TITLE
Zombies not Spawning when another players connect

### ISSUE THREAD

**Issue by ghost** [FiveM-Scripts/CorruptSnail-Gamemode#8]
When another player connects zombie/guards won't spawn anymore unless other player(s) leaves and resource is restarted

ERROR: cl_player.lua:10: attempt to index a nil value (global 'Util')
> func (@CorruptSnail-Gamemode/spawning/cl_savezones.lua:68)
> fn (@CorruptSnail-Gamemode/cl_utils.lua:130)

ERROR: cl_player.lua:10: attempt to index a nil value (global 'Util')
> func (@CorruptSnail-Gamemode/spawning/cl_zombies.lua:253)
> fn (@CorruptSnail-Gamemode/cl_utils.lua:130)

**Comment by ghost** [comment]
```
 for _, playerId in ipairs(GetActivePlayers()) do
        if playerId ~= nil then
            if GetPlayerServerId(playerId) > mServerId and Util.GetDistanceBetweenCoords(mPlayerPedPos, GetEntityCoords(GetPlayerPed(playerId))) <= Config.Spawning.HOST_DECIDE_DIST then
                return false
            end
        end
    end
```

I put a nil there and it made the same error without other players

**Comment by Switty6** [comment]
Check in your config file if you accidentally deleted any commas. That seems to be the problem
